### ISSUE TITLE
should describe the experiments in the contextual-choice notebook in greater detail

### ISSUE THREAD

**Issue by qihongl** [qihongl/dnd-lstm#1]

**Comment by ghost** [comment]
Could you describe it?  Thanks!

**Comment by qihongl** [comment]
@cubicgate

Yes! lol! I'm sorry. Thanks for asking! I totally forgot this. I will update the notebook later. But here's a short version: 

It is an evidence accumulation task with "context"
In the i-th trial, 
- at time t, the model receives noisy observation, x_t (e.g. random dots moving around, slightly drifting to left/right)
- and a "context vector" for this trial, call it context_i (e.g. an image of an apple)
- the task is to judge if the sum of the observation sequence is positive or negative. Let's denote this target by y_i (e.g. left/right button press)

If I haven't seen trial i before. I have to integrate x_t over time  - evidence accumulation. 
And because context_i is always paired with y_i by task design, so if I have seen trial i before, and remember that the target for context_i (e.g. image of an apple) is y_i (left button press).  Then there is no need to do evidence accumulation, you can just pick y_i. The model wants to respond earlier because this reduces the loss, but this is only possible if the model stored (context_i, y_i) into its episodic memory buffer (DND).

**Comment by ghost** [comment]
Thanks Qihong for your good explanation.  Do you mind helping me to learn your sine example?  Thanks!

**Comment by qihongl** [comment]
Sure let me know if I can help with anything! 

btw I wrote this with A2C, and I plan to add more examples to this repo when I have more time...
