### ISSUE TITLE
Code and 　README.md　 are inconsistent

### ISSUE THREAD

**Issue by leslie27ch** [qihongl/dnd-lstm#4]
Ｈｅｌｌｏ，may i ask you a question?

in  **README.md** , you said : model stored (cue_i, y_i) into its episodic memory buffer (DND).

but in your **code,** you only store the last time step x_t of a trial . this is not a cue of a task .
self.dnd.save_memory(x_t, c_t)

so i suppose the code can't complete the task as you expect.

can you give me some information why you implement your code like this ?

thank you .

**Comment by qihongl** [comment]
Thanks for the question! What I wrote in README is a conceptual description / what the model suppose to do (not even pseudocode). I can see that's potentially confusing. I will modify it later. 

Regarding your questions: 
- The cue for the i-th trial is in x_t, so the cue is constantly presented to the model. i.e. saving x_t implies saving the cue. 
- c_t at the last timestep encodes y_i, as shown by the PCA analysis.
