### ISSUE TITLE
DND differences with the one in Neural Episodic Control

### ISSUE THREAD

**Issue by richielo** [qihongl/dnd-lstm#5]
Hello, Thanks for the nice codebase. I'd just like to confirm some of the differences I see from this DND implementation with the NEC paper's:

1. This version reads one value out of the dictionary instead of a weighted sum 
2. KD-Tree is not used for lookup 

Am I missing anything? 

Side question, what do you by DND is not fully differentiable? Thanks a lot in advance.

**Comment by qihongl** [comment]
Thanks for the question @richielo !

Ritter (2018) uses 1NN so I did the same (no weighting needed), but I also wanted to have the option to get a weighted sum of memories so I have a function to compute the similarities with all memories 
https://github.com/qihongl/dnd-lstm/blob/master/src/model/DND.py#L148

and get memory function gets the similarity value 
https://github.com/qihongl/dnd-lstm/blob/master/src/model/DND.py#L118
if you multiply it with the memory matrix, it will give you a weighted sum of memories. In some other memory model, that's what I did. 

Thanks!

**Comment by richielo** [comment]
Understood. Thank you for the prompt reply! Just a quick side question, from your experience, do you see a significant performance improvement when you replace the best matching memory with a weighted sum of best-n memories?

**Comment by qihongl** [comment]
@richielo thanks for the question! 

It depends on the task -- If 1 and only 1 memory is relevant to the ongoing situation most of the time, then 1NN is better. If the environment requires averaging over multiple memories (maybe need to compute an average state value based on past memories and a single memory is too noisy), then averaging over multiple memories is useful. I implemented a parameter to allow the model to interpolate between 1NN vs. averaging and optimized it as a hyperparameter.

**Comment by richielo** [comment]
Very interesting! Is that piece of code openly available ?

**Comment by qihongl** [comment]
yes: https://github.com/qihongl/learn-hippo
and here's the model: https://github.com/qihongl/learn-hippo/blob/master/src/models/LCALSTM.py

that said I'm trying to model human behavior and I'm not sure if the model is useful for AI/ML tasks, since I incorporated some cognitive/neuro-constraints

**Comment by richielo** [comment]
Got it and thanks a lot! Will give it a try

**Comment by qihongl** [comment]
my pleasure! looking forward to it! =)
